dist: trusty
services:
  - mysql
env:
  - NODE_ENV=travis
language: node_js
node_js:
  - 8
  - node
cache: yarn
install:
  - yarn && cd frontend && yarn && cd -
script:
  - yarn lint
  - yarn build
  - yarn build:aot
  - yarn e2e:ci

