dist: trusty
services:
  - mysql
addons:
  chrome: stable
env:
  - NODE_ENV=travis
language: node_js
node_js:
  - 8
  - node
cache: yarn
install:
  - yarn && cd frontend && yarn && cd -
script:
  - yarn lint
  - yarn build
  - yarn build:aot
  - ./server.js &
  - cd frontend && yarn e2e:headless && cd -
  - killall node
