dist: trusty
services:
  - mysql
addons:
  chrome: stable
env:
  - NODE_ENV=travis
language: node_js
node_js:
  - 8
  - node
cache: yarn
install:
  - yarn && cd frontend && yarn && cd -
before_script:
  - yarn global add gulp
script:
  - yarn lint
  - yarn build
  - yarn build:aot
  - ./ci-e2e-test.sh
