# -*- coding: utf-8 -*-

commonSpecials = {
  'Immunities': 'Abominations are immune to polymorphing, petrification, or any form-altering attack. They are not subject to energy drain, ability drain, or ability damage. They are immune to mind-affecting effects (charms, compulsions, phantasms, patterns, and morale effects), and are immune to one of five energy types (specific to the abomination).',
  'Resistances': 'Abominations have fire resistance 20, cold resistance 20, and damage reduction of at least 10/epic (certain abominations have higher damage reduction). Abominations all have significant spell resistance. Abominations resist detection, and are all treated as if affected by a nondetection spell of a caster level equal to the abomination’s HD.',
  'Telepathy': 'Abominations can communicate telepathically with any creature within 1,000 feet that has a language.',
  'Special Qualities': 'All abominations have the spell-like ability to use true seeing at will. Abominations are not subject to death from massive damage, and they have maximum hit points per Hit Die. Abominations have the blindsight extraordinary ability to a range of 500 feet. Abominations can choose both nonepic and epic feats as part of their feat selection.',
  'Summon Creature': 'Abominations can summon creatures associated either with the portfolio of their godly progenitor or with their imprisonment. Summoned creatures serve the abomination without question. Summoned creatures automatically return whence they came after 1 hour, or sooner if slain. See specific abomination entries for additional details on summoning.',
  'Antimagic Field': 'A colossus constantly generates an antimagic field in a 100-foot-radius. The field is an invisible barrier that is impervious to most magical effects, including spells, spell-like abilities, and supernatural abilities. Likewise, it prevents the functioning of any magic items or spells within its confines, except for the colossus’s own supernatural abilities. This effect is otherwise as an antimagic field cast by a 25th-level caster.',
  'Blindsense': 'Dragons can pinpoint creatures within a distance of 60 feet. Opponents the dragon can’t actually see still have total concealment against the dragon.',
  'Crush': 'This special attack allows a flying or jumping dragon of at least Huge size to land on opponents as a standard action, using its whole body to crush them. Crush attacks are effective only against opponents three or more size categories smaller than the dragon (though it can attempt normal overrun or grapple attacks against larger opponents). A crush attack affects as many creatures as can fit under the dragon’s body. Creatures in the affected area must succeed on a Reflex save (DC equal to that of the dragon’s breath weapon) or be pinned, automatically taking bludgeoning damage during the next round unless the dragon moves off them. If the dragon chooses to maintain the pin, treat it as a normal grapple attack. Pinned opponents take damage from the crush each round if they don’t escape. A crush attack deals the indicated damage plus 1-1/2 times the dragon’s Strength bonus (round down).',
  'Tail Sweep': 'This special attack allows a dragon of at least Gargantuan size to sweep with its tail as a standard action. The sweep affects a half-circle with a radius of 30 feet (or 40 feet for a Colossal dragon), extending from an intersection on the edge of the dragon’s space in any direction. Creatures within the swept area are affected if they are four or more size categories smaller than the dragon. A tail sweep automatically deals the indicated damage plus 1-1/2 times the dragon’s Strength bonus (round down). Affected creatures can attempt Reflex saves to take half damage (DC equal to that of the dragon’s breath weapon).',
  'Frightful Presence': 'A young adult or older dragon can unsettle foes with its mere presence. The ability takes effect automatically whenever the dragon attacks, charges, or flies overhead. Creatures within a radius of 30 feet x the dragon’s age category are subject to the effect if they have fewer HD than the dragon. A potentially affected creature that succeeds on a Will save (DC 10 + 1/2 dragon’s HD + dragon’s Cha modifier) remains immune to that dragon’s frightful presence for 24 hours. On a failure, creatures with 4 or less HD become panicked for 4d6 rounds and those with 5 or more HD become shaken for 4d6 rounds. Dragons ignore the frightful presence of other dragons.',
  'Keen Senses': 'A dragon sees four times as well a human in shadowy illumination and twice as well in normal light. It also has darkvision out to 120 feet.',
  'Spell Resistance': 'For standard advanced dragons, spell resistance increases by 2 per additional age category. For epic dragons, spell resistance increases by 3 (for force dragons) or 6 (for prismatic dragons) per additional age category.',
  'Plane Shift': 'A genie can enter any of the elemental planes, the Astral Plane, or the Material Plane. This ability transports the genie and up to eight other creatures, provided they all link hands with the genie. It is otherwise similar to the spell of the same name (caster level 13th).',
  'Rock Throwing': 'Adult giants are accomplished rock throwers and receive a +1 racial bonus on attack rolls when throwing rocks. A giant of at least Large size can hurl rocks weighing 40 to 50 pounds each (Small objects) up to five range increments. The size of the range increment varies with the giant’s variety. A Huge giant can hurl rocks of 60 to 80 pounds (Medium objects).',
  'Rock Catching': 'A giant of at least Large size can catch Small, Medium, or Large rocks (or projectiles of similar shape). Once per round, a giant that would normally be hit by a rock can make a Reflex save to catch it as a free action. The DC is 15 for a Small rock, 20 for a Medium one, and 25 for a Large one. (If the projectile provides a magical bonus on attack rolls, the DC increases by that amount.) The giant must be ready for and aware of the attack in order to make a rock catching attempt.',
  'Fast Healing': 'An inevitable heals a certain amount of damage each round (specified in each variety’s description) as long as it has at least 1 hit point. However, damage dealt by chaotic weapons heals at the normal rate.',
  'Summon Mephit': 'Once per day, a mephit can attempt to summon another mephit of the same variety, much as though casting a summon monster spell, but with only a 25% chance of success. Roll d%: On a failure, no creature answers the summons that day. A mephit that has just been summoned cannot use its own summon ability for 1 hour. This ability is the equivalent of a 2nd-level spell.',
  'Aversion to Daylight': 'If exposed to natural daylight (not merely a daylight spell), nightshades take a –4 penalty on all attack rolls, saving throws, and skill checks.',
  'Desecrating Aura': 'All nightshades give off a 20-footradius emanation of utter desecration, imbuing their surroundings with negative energy. This ability works much like a desecrate spell, except that the nightshade’s evil is so great that it is treated as the shrine of an evil power. All undead within 20 feet of the nightshade (including the creature itself ) gain a +2 profane bonus on attack rolls, damage rolls, and saving throws, and +2 hit points per HD. (The nightshade Hit Dice, attack, and save entries given here include these profane bonuses.) Charisma checks made to turn undead within this area take a –6 penalty.',
  'Blindsight': 'An ooze’s entire body is a primitive sensory organ that can ascertain prey by scent and vibration within 60 feet.',
  'Pounce': 'If a sphinx charges a foe, it can make a full attack, including two rake attacks.',

}
