apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"3"},"creationTimestamp":"2019-08-18T17:06:15Z","generation":3,"labels":{"app":"d20md"},"name":"d20md","namespace":"d20md","resourceVersion":"2748915","selfLink":"/apis/extensions/v1beta1/namespaces/d20md/deployments/d20md","uid":"ba78b24e-cba4-426d-8e1b-822f6368c9ee"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"d20md"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"d20md"}},"spec":{"containers":[{"env":[{"name":"DB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"mysql-credentials"}}}],"image":"sirwojtek/d20md:latest","imagePullPolicy":"Always","name":"d20md","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/root/.aws","name":"aws-credentials","readOnly":true}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":600,"volumes":[{"name":"aws-credentials","secret":{"defaultMode":420,"secretName":"aws-credentials"}}]}}},"status":{"conditions":[{"lastTransitionTime":"2019-08-18T17:06:15Z","lastUpdateTime":"2019-08-21T14:44:08Z","message":"ReplicaSet \"d20md-84df76ff55\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2019-08-21T14:56:32Z","lastUpdateTime":"2019-08-21T14:56:32Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"}],"observedGeneration":3,"replicas":1,"unavailableReplicas":1,"updatedReplicas":1}}
  creationTimestamp: "2019-08-18T17:06:15Z"
  generation: 4
  labels:
    app: d20md
  name: d20md
  namespace: d20md
  resourceVersion: "2749538"
  selfLink: /apis/extensions/v1beta1/namespaces/d20md/deployments/d20md
  uid: ba78b24e-cba4-426d-8e1b-822f6368c9ee
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: d20md
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: d20md
    spec:
      containers:
      - env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: database
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
        image: sirwojtek/d20md:latest
        imagePullPolicy: Always
        name: d20md
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/.aws
          name: aws-credentials
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 600
      volumes:
      - name: aws-credentials
        secret:
          defaultMode: 420
          secretName: aws-credentials
status:
  conditions:
  - lastTransitionTime: "2019-08-18T17:06:15Z"
    lastUpdateTime: "2019-08-21T14:59:33Z"
    message: ReplicaSet "d20md-55db6fb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-08-21T15:03:49Z"
    lastUpdateTime: "2019-08-21T15:03:49Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 4
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
